# Generated by Django 4.2.3 on 2023-08-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='user.jpg', upload_to='profile_photos'),
        ),
    ]
